import { NextPage } from "next";
import Head from "next/head";
import SerachForm from "../components/SerachForm/SerachForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SerachForm />
    </>
  );
};

export default Home;
